Fix inclusion of system provided status code
ned14/outcome pull request #269
Opened 2022-07-19 08:54 UTC by BurningEnlightenment

These popped up while intergrating with vcpkg, see commit messages.

2022-08-12 16:11 UTC, BurningEnlightenment commented
@ned14 this is ready for review now.

2022-08-12 17:28 UTC, ned14 requested changes

2022-08-12 17:28 UTC, ned14 commented on include/outcome/experimental/coroutine_support.hpp
> +#if !OUTCOME_USE_SYSTEM_STATUS_CODE && __has_include("status-code/include/system_code_from_exception.hpp")
Path correct?

2022-08-12 18:03 UTC, BurningEnlightenment commented on include/outcome/experimental/coroutine_support.hpp
> +#if !OUTCOME_USE_SYSTEM_STATUS_CODE && __has_include("status-code/include/system_code_from_exception.hpp")
Whoops, fixed.

2022-08-18 14:03 UTC, ned14 approved these changes

2022-08-18 14:04 UTC, merged